name: emergency
description: International Emergency Number.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it:

  # Functional
  dartz:

  # Bloc for state management
  flutter_bloc:

  # Network
  http: ^0.12.0+1
  data_connection_checker:

  # Local cache
  shared_preferences:

  # Local database 
  sqflite:
  path:

  # Firebase
  firebase_core: 0.4.4
  firebase_analytics: ^1.0.4
  firebase_messaging: ^5.0.2
  cloud_firestore: ^0.12.10

  # Launcher
  url_launcher:
  maps_launcher:

  # UI
  flutter_slidable: ^0.5.4

  # Etc
  equatable:
  device_info:
  logger:
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
    # Mock
  mockito:

flutter:
  uses-material-design: true
  assets:
      - images/ic_search_small.png
      - images/ic_call.png
      - images/ic_fire.png
      - images/ic_hospital.png
      - images/ic_mail.png
      - images/ic_pin_blue.png
      - images/ic_police.png
      - images/ic_arrow_up.png
      - images/ic_arrow_down.png
      - images/btn_back_gray.png
      - images/btn_search_big.png
      - images/btn_clear.png
      - images/btn_back_white.png
      - images/btn_alarm_on.png
      - images/btn_alarm_off.png
      - images/btn_more.png
      - images/btn_plus.png
      - images/btn_setting.png
      - images/btn_right.png